### ISSUE TITLE
set up a basic CI system.

### ISSUE THREAD

**Issue by Spindel** [kevin-civic/civic_news#4]
For GitHub, [Travis CI](https://docs.travis-ci.com/user/getting-started/) is the recommended

Set up a basic CI pipeline that:  
- [x]  installs the application with `pip install .`   

This is the "Hello World" verion of a CI system, but requires you to read up a bit on getting the basics running.  

A minimal Travis setup looks like:

```
  language: python
  python:
    - 3.6
    - nightly
  script:
    - pip install -r requirements.txt
    - pip install .
```

There's one in the Django template that should work, you can use that.
Sign up for travis, and get that running.
